core/urls.py
from django.conf.urls import patterns, include, url
from . import views

urlpatterns = patterns('',
    url(r'^events/$', views.events, name='events'),
    url(r'^resources/$', views.resources, name='resources'),
    url(r'^organize/$', views.organize, name='organize'),
    url(r'^story/$', views.stories, name='stories'),

    url(r'^(?P<city>[\w\d/]+)$', 'core.views.event', name='event'),
    url(r'^$', views.index, name='index'),
)

djangogirls/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Redirect old links:
    url(r'^pages/in-your-city/$', RedirectView.as_view(url='/organize/', permanent=True)),
    url(r'^admin$', RedirectView.as_view(url='/admin/', permanent=True)),

    # Regular links:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'', include('core.urls', namespace='core')),
)

templates/global/base.html
{% load staticfiles %}
<!DOCTYPE HTML>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
  <title>{% block title %}Django Girls - start your journey with programming{% endblock %}</title>
  <meta name="description" content="Django Girls is a one-day workshop about programming in Python and Django for women.">
  <meta name="keywords" content="programming, python, django, workshop, women, females">
  <link href="{% static 'img/favicon.ico' %}" rel="shortcut icon">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta property="og:title" content="Django Girls is a one-day workshop about programming in Python and Django for women" />
  <meta property="og:type" content="website" />
  <meta property="og:description" content="Join us and become female developer! Build your first website in Python and Django in a friendly, safe enviroment." />
  <meta property="og:url" content="http://djangogirls.org/" />
  <meta property="og:image" content="https://raw.githubusercontent.com/olasitarska/djangogirls/gh-pages/resources/graphics/logo_square.png" />

  <link rel="stylesheet" href="//brick.a.ssl.fastly.net/Linux+Libertine:400,600,700,400i,600i,700i/Roboto:300,400,300i,400i">
  <link rel="stylesheet" type="text/css" href="{% static 'vendor/css/bootstrap.min.css' %}" media="screen">
  <link rel="stylesheet" type="text/css" href="{% static 'vendor/css/sss.css' %}" media="screen">
  <link rel="stylesheet" type="text/css" href="{% static 'css/global.css' %}" media="screen">
  <script type="text/javascript" src="{% static 'vendor/js/jquery.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'vendor/js/sss.min.js' %}"></script>
  {% block extra_js %}{% endblock %}
</head>
<body>
    <div class="page-wrap">
        {% block menu %}
            {% include 'global/menu.html' %}
        {% endblock %}

        {% block content %}{% endblock %}
    </div>

    {% block footer %}
        {% include 'global/footer.html' %}
    {% endblock %}

    {% include 'includes/js.html' %}
</body>
</html>

templates/global/footer.html
<footer>
    <div class="container">
        <div class="row">

            <div class="col-md-3">
                <p>Django Girls</p>
                <ul>
                    <li><a href="{% url 'core:events' %}">Events</a></li>
                    <li><a href="{% url 'core:stories' %}">Stories</a></li>
                    <li><a href="{% url 'core:resources' %}">Resources</a></li>
                    <li><a href="{% url 'core:organize' %}">Organize</a></li>
                    <li><a href="mailto:hello@djangogirls.org">hello@djangogirls.org</a></li>
                </ul>
            </div>

            <div class="col-md-3">
                <p>Community</p>
                <ul>
                    <li><a href="http://facebook.com/djangogirls">Facebook</a></li>
                    <li><a href="http://twitter.com/djangogirls">Twitter</a></li>
                    <li><a href="http://github.com/djangogirls">Github</a></li>
                    <li><a href="http://community.djangogirls.org/">Discussions</a></li>
                    <li><a href="/pages/coc/">Code of Conduct</a></li>
                </ul>
            </div>

            <div class="col-md-3">
                <p>Resources</p>
                <ul>
                    <li><a href="http://tutorial.djangogirls.org/">Tutorial</a></li>
                    <li><a href="http://organize.djangogirls.org/">Organizer's Manual</a></li>
                    <li><a href="http://coach.djangogirls.org/">Coaching Guide</a></li>
                    <li><a href="http://djangogirls.gitbooks.io/django-girls-tutorial-extensions/">Tutorial Extensions</a></li>
                    <li><a href="https://github.com/DjangoGirls/resources">Graphics</a></li>
                </ul>
            </div>

            <div class="col-md-3">
                <p>♥</p>
                <ul>
                    <li><b>{{ future_events_count }}</b> upcoming events</li>
                    <li><b>{{ past_events_count }}</b> past events</li>
                    <li><b>{{ applicants_sum }}</b> applicants</li>
                    <li><b>{{ attendees_sum }}</b> attendees</li>
                    <li><b>{{ countries_count }}</b> countries</li>
                </ul>
            </div>

        </div>
    </div>
</footer>

templates/global/menu.html
{% load staticfiles %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <nav role="navigation" class="clearfix">
                <div class="logo">
                    <a href="/">
                        <img src="{% static 'img/global/logo.png' %}" alt="Django Girls" />
                    </a>
                </div>

                <ul>
                    <li><a href="{% url 'core:events' %}">Events</a></li>
                    <li><a href="{% url 'core:stories' %}">Stories</a></li>
                    <li><a href="{% url 'core:resources' %}">Resources</a></li>
                    <li><a href="{% url 'core:organize' %}">Organize</a></li>
                    <li><a href="http://blog.djangogirls.org/">Blog</a></li>
                </ul>
            </nav>
        </div>
    </div>
</div>