core/urls.py
from django.conf.urls import patterns, include, url
from . import views

urlpatterns = patterns('',
    url(r'^events/$', views.events, name='events'),
    url(r'^resources/$', views.resources, name='resources'),
    url(r'^organize/$', views.organize, name='organize'),
    url(r'^story/$', views.stories, name='stories'),

    url(r'^(?P<city>[\w\d/]+)$', 'core.views.event', name='event'),
    url(r'^$', views.index, name='index'),
)

djangogirls/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Redirect old links:
    url(r'^pages/in-your-city/$', RedirectView.as_view(url='/organize/', permanent=True)),
    url(r'^admin$', RedirectView.as_view(url='/admin/', permanent=True)),

    # Regular links:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^pages/', include('django.contrib.flatpages.urls')),
    url(r'', include('core.urls', namespace='core')),
)

core/models.py
from datetime import datetime

from django.db import models
from django.contrib.auth import models as auth_models
from django.contrib.auth.models import User

from django_date_extensions.fields import ApproximateDateField

class UserManager(auth_models.BaseUserManager):
    def create_user(self, email, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        user = self.model(email=self.normalize_email(email))
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(email, password=password)
        user.is_superuser = user.is_staff = True
        user.save(using=self._db)
        return user


class User(auth_models.AbstractBaseUser, auth_models.PermissionsMixin):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Organizer'
        verbose_name_plural = 'Organizers'

    def __unicode__(self):
        return u'{0} ({1})'.format(self.get_full_name(), self.email)

    def get_short_name(self):
        return self.first_name

    def get_full_name(self):
        return u'{0} {1}'.format(self.first_name, self.last_name)

class EventManager(models.Manager):

    def future(self):
        return super(EventManager, self).get_queryset().filter(is_on_homepage=True, date__gte=datetime.now().strftime('%Y-%m-%d')).order_by('date')

    def past(self):
        return super(EventManager, self).get_queryset().filter(is_on_homepage=True, date__lt=datetime.now().strftime('%Y-%m-%d')).order_by('-date')


class Event(models.Model):
    name = models.CharField(max_length=200, null=False, blank=False)
    date = ApproximateDateField(null=True, blank=True)
    city = models.CharField(max_length=200, null=False, blank=False)
    country = models.CharField(max_length=200, null=False, blank=False)
    latlng = models.CharField(max_length=30, null=True, blank=True)
    photo = models.ImageField(upload_to="event/cities/", null=True, blank=True, help_text="The best would be 356 x 210px")
    photo_credit = models.CharField(max_length=200, null=True, blank=True)
    main_organizer = models.ForeignKey(User, null=True, blank=True, related_name="main_organizer")
    team = models.ManyToManyField(User, null=True, blank=True)
    is_on_homepage = models.BooleanField(default=False)

    objects = EventManager()

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = "List of events"

class EventPage(models.Model):
    event = models.OneToOneField(Event, primary_key=True)
    title = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True, default='Django Girls is a one-day workshop about programming in Python and Django tailored for women.')
    main_color = models.CharField(max_length=6, null=True, blank=True, help_text='Main color of the chapter in HEX', default='FF9400')
    custom_css = models.TextField(null=True, blank=True)
    url = models.CharField(max_length=200, null=True, blank=True)

    is_live = models.BooleanField(null=False, blank=False, default=False)

    def __unicode__(self):
        return 'Website for %s' % self.event.name

    class Meta:
        verbose_name = "Website"

class EventPageContent(models.Model):
    page = models.ForeignKey(EventPage, null=False, blank=False)
    name = models.CharField(null=False, blank=False, max_length=100)
    content = models.TextField(null=False, blank=False, help_text="HTML allowed")
    background = models.ImageField(upload_to="event/backgrounds/", null=True, blank=True, help_text="Optional background photo")
    position = models.PositiveIntegerField(null=False, blank=False, help_text="Position of the block on the website")

    is_public = models.BooleanField(null=False, blank=False, default=False)

    def __unicode__(self):
        return "%s at %s" % (self.name, self.page.event)

    class Meta:
        ordering = ('position', )
        verbose_name = "Website Content"


class EventPageMenu(models.Model):
    page = models.ForeignKey(EventPage, null=False, blank=False)
    title = models.CharField(max_length=255, null=False, blank=False)
    url = models.CharField(max_length=255, null=False, blank=False)
    position = models.PositiveIntegerField(null=False, blank=False, help_text="Order of menu")

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ('position', )
        verbose_name = "Website Menu"

class Sponsor(models.Model):
    event_page_content = models.ForeignKey(EventPageContent, null=False, blank=False)
    name = models.CharField(max_length=200, null=True, blank=True)
    logo = models.ImageField(upload_to="event/sponsors/", null=True, blank=True, help_text="Make sure logo is not bigger than 200 pixels wide")
    url = models.URLField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)

    position = models.PositiveIntegerField(null=False, blank=False, help_text="Position of the sponsor")

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ('position', )

class Coach(models.Model):
    event_page_content = models.ForeignKey(EventPageContent, null=False, blank=False)
    name = models.CharField(max_length=200, null=False, blank=False)
    twitter_handle = models.CharField(max_length=200, null=True, blank=True, help_text="No @, No http://, just username")
    photo = models.ImageField(upload_to="event/coaches/", null=True, blank=True, help_text="For best display keep it square")
    url = models.URLField(null=True, blank=True)


    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ('?',)
        verbose_name_plural = "Coaches"

class Postmortem(models.Model):
    event = models.ForeignKey(Event, null=False, blank=False)
    attendees_count = models.IntegerField(null=False, blank=False, verbose_name="Number of attendees")
    applicants_count = models.IntegerField(null=False, blank=False, verbose_name="Number of applicants")

    discovery = models.TextField(null=True, blank=True, verbose_name="What was the most important thing you discovered during the workshop?")
    feedback = models.TextField(null=True, blank=True, verbose_name="How we can make DjangoGirls better?")
    costs = models.TextField(null=True, blank=True, verbose_name="What are the total costs of the event?", help_text="We only collect this information for statistics and advice for future organizers.")
    comments = models.TextField(null=True, blank=True, verbose_name="Anything else you want to share with us?")

    def __unicode__(self):
        return self.event.city

class Story(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    post_url = models.URLField(null=False, blank=False)
    image = models.ImageField(upload_to="stories/", null=False, blank=False)
    created = models.DateField(auto_now_add=True, null=False, blank=False)

    def __unicode__(self):
        return self.name

templates/includes/_coach.html
<a href="{{ coach.url }}" target="_blank">
    {% if coach.photo %}
        <img src="{{ coach.photo.url }}" alt="{{ coach.name }}" class="coach" />
    {% endif %}
</a><br />
<a href="{{ coach.url }}" target="_blank">{{ coach.name }}</a><br />
{% if coach.twitter_handle %}<a href="{{ coach.url }}" target="_blank">@{{ coach.twitter_handle }}</a><br />{% endif %}

templates/includes/_event.html
{% if event.eventpage.is_live %}<a href="/{{ event.eventpage.url }}">{% endif %}
    <div class="col-md-4 event"{% if event.photo %} style="background-image: url({{ event.photo.url }})"{% endif %}>
        <div class="overlay">
            <p class="city">{{ event.city }}</p>
            <span class="date">{{ event.date }}</span>
            {% if event.photo_credit %}<p class="credit">Photo credit: {{ event.photo_credit }}</p>{% endif %}
        </div>
    </div>
{% if event.eventpage.is_live %}</a>{% endif %}

templates/includes/_no_event.html
<div class="row">
    <div class="col-md-12">
        <h2>Don’t see event in your city?</h2>
    </div>
</div>

<div class="row centered">
    <div class="col-md-12">
        <h4>Sign up for newsletter</h4>
        <p>
            We will let you know when the event in your city will be launched:
        </p>
        <form action="//djangogirls.us8.list-manage.com/subscribe/post?u=5a007b2dabdeddc350bdbbaed&amp;id=8c50a4b2d0" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
            <input type="email" name="EMAIL" placeholder="Your e-mail" />
            <input type="text" name="CITY" placeholder="Your city" />
            <input type="submit" value="Sign up" name="subscribe" />
            <div style="position: absolute; left: -5000px;"><input type="text" name="b_5a007b2dabdeddc350bdbbaed_8c50a4b2d0" tabindex="-1" value=""></div>
        </form>
    </div>
</div>

<div class="row centered">
    <div class="col-md-12">
        <h4>Bring Django Girls to your city!</h4>
        <p>
            Everyone can organize their own Django Girls event and share it with their community.
        </p>
        <a href="{% url 'core:organize' %}" class="btn">Find out more</a>
    </div>
</div>

templates/includes/_sponsor.html
<div class="col-md-3">
    <a href="{{ sponsor.url }}" target="_blank">
        {% if sponsor.logo %}
            <img src="{{ sponsor.logo.url }}" alt="{{ sponsor.name }}" />
        {% else %}
            <b>{{ sponsor.name }}</b>
        {% endif %}
    </a>
    {% if sponsor.description %}<p>{{ sponsor.description }}</p>{% endif %}
</div>
{% if forloop.counter|divisibleby:4 %}</div><div class="row sponsor-logos">{% endif %}

templates/includes/_story.html
<a href="{{ story.post_url }}" target="_blank">
    <div class="col-md-3 girl" style="background-image: url({% if story.image %}{{ story.image.url }}{% endif %});">
        <div class="overlay">{{ story.name }}</div>
    </div>
</a>

templates/includes/item.html
{% if item.background %}

    <div id="{{ item.name }}" class="with-background" style="background-image: url({{ item.background.url }})">
        <div class="overlay">
              <div class="container">
                  {{ item.content|safe }}
              </div>
          </div>
    </div>

{% else %}

    <div class="container without-background" id="{{ item.name }}">
        {{ item.content|safe }}

        {% if item.sponsor_set.count > 0 %}
            <div class="row sponsor-logos">
                {% for sponsor in item.sponsor_set.all %}
                    {% include 'includes/_sponsor.html' with sponsor=sponsor %}
                {% endfor %}
            </div>
        {% endif %}

        {% if item.coach_set.count > 0 %}
            <div class="row coaches">

                {% for coach in item.coach_set.all %}
                    <div class="col-md-2{% cycle ' col-md-offset-1' '' '' '' '' %}">
                        {% include 'includes/_coach.html' with coach=coach %}
                    </div>

                    {% if forloop.counter|divisibleby:5 %}</div><div class="row coaches">{% endif %}
                {% endfor %}

            </div>
        {% endif %}

    </div>

{% endif %}

templates/includes/js.html
<!-- fb -->
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "http://connect.facebook.net/en_US/all.js#xfbml=1&appId=345022845576638";
        fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
<!-- twitter -->
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
<!-- analytics -->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-51680040-1', 'djangogirls.org');
      ga('send', 'pageview');

    </script>